// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTP31Muvs8m9FycUP03omKynlrwvyB5Q',
    appId: '1:208045247907:web:0934d44f78d1aa821d9e16',
    messagingSenderId: '208045247907',
    projectId: 'fir-memo-app-81fa4',
    authDomain: 'fir-memo-app-81fa4.firebaseapp.com',
    storageBucket: 'fir-memo-app-81fa4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAu2utuiLgxgm0_jcfGamzDhKyA-MO3Q',
    appId: '1:208045247907:android:0fc236dcee35ec451d9e16',
    messagingSenderId: '208045247907',
    projectId: 'fir-memo-app-81fa4',
    storageBucket: 'fir-memo-app-81fa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonObr35Sknk5Wkmt_NM7qYtV5Vuhfpgc',
    appId: '1:208045247907:ios:59e22312fbbab33f1d9e16',
    messagingSenderId: '208045247907',
    projectId: 'fir-memo-app-81fa4',
    storageBucket: 'fir-memo-app-81fa4.appspot.com',
    iosClientId: '208045247907-1pbgbdcejalt54vt56q8kk4bd254qe8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMemmoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBonObr35Sknk5Wkmt_NM7qYtV5Vuhfpgc',
    appId: '1:208045247907:ios:59e22312fbbab33f1d9e16',
    messagingSenderId: '208045247907',
    projectId: 'fir-memo-app-81fa4',
    storageBucket: 'fir-memo-app-81fa4.appspot.com',
    iosClientId: '208045247907-1pbgbdcejalt54vt56q8kk4bd254qe8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMemmoApp',
  );
}
